apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sdwc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seongmin15/sdwc-platform
    targetRevision: main
    path: manifests/sdwc
  destination:
    server: https://kubernetes.default.svc
    namespace: sdwc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
